- name: Install EPEL repository
  ansible.builtin.yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux 7 - $basearch
    baseurl: https://dl.fedoraproject.org/pub/epel/7/$basearch
    gpgcheck: yes
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    enabled: yes

- name: Install remi-release RPM
  ansible.builtin.yum_repository:
    name: remi
    description: Remi's RPM repository for Enterprise Linux 7 - $basearch
    baseurl: http://rpms.remirepo.net/enterprise/7/remi/$basearch/
    gpgcheck: yes
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    enabled: yes
    state: present

- name: Enable remi-php80 repository
  ansible.builtin.yum_repository:
    name: remi-php80
    description: Remi's PHP 8.0 RPM repository for Enterprise Linux 7 - $basearch
    baseurl: http://rpms.remirepo.net/enterprise/7/php80/$basearch/
    gpgcheck: yes
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    enabled: yes
    state: present

- name: Install Packages for WordPress
  ansible.builtin.yum:
    name:
      - php 
      - httpd
      - php-pear
      - php-cgi
      - php-common
      - php-curl
      - php-mbstring
      - php-gd
      - php-mysqlnd
      - php-bcmath
      - php-json
      - php-xml
      - php-intl
      - php-zip
      - php-imap
    state: present

  
- name: Enable and start httpd service
  ansible.builtin.service:
    name: httpd
    enabled: true
    state: started

- name: Change file ownership, group, and permissions
  ansible.builtin.file:
    path: /var/www/html
    owner: vagrant
    group: apache
    mode: '0664'
    recurse: true

- name: Unarchive WordPress
  ansible.builtin.unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html/
    remote_src: yes
    owner: vagrant
    group: apache
    extra_opts: [--strip-components=1]

- name: Update Config  
  ansible.builtin.template:  
    src: wp-config.php.j2  
    dest: /var/www/html/wp-config.php

- name: Change file ownership, group, and permissions
  ansible.builtin.file:
    path: /var/www/html
    owner: vagrant
    group: apache
    mode: u=rwX,g=rwX,o=rX 
    recurse: true
      
- name: Remove old index
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: Enable .htaccess files in Apache config
  ansible.builtin.replace:
    path: /etc/httpd/conf/httpd.conf
    after: '<Directory "/var/www/html">'
    before: '</Directory>'
    regexp: 'AllowOverride None'
    replace: 'AllowOverride All'
  notify:
    - restart apache2
  
- name: Install required Python library
  ansible.builtin.yum:
    name: libsemanage-python
    state: present

- name: Enable remote connection to DB
  ansible.builtin.seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes
  notify:
    - restart apache2