wordpress_db: wordpress
wordpress_user: wordpress
wordpress_password: wordpress_password
mysql_root_password: root
mysql_host: 192.168.33.11

mysql_databases:
  - name: "{{wordpress_db}}"
mysql_users:
  - name: "{{wordpress_user}}"
    host: "%"
    password: "{{wordpress_password}}"
    priv: "{{wordpress_user}}.*:ALL"