- hosts: dbservers
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - role: geerlingguy.mysql


- hosts: webservers
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - role: wordpress